#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$CUSTOM_POSTGRES_USER";
    ALTER USER "$CUSTOM_POSTGRES_USER" WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE "$CUSTOM_POSTGRES_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$CUSTOM_POSTGRES_DB" TO "$CUSTOM_POSTGRES_USER";
EOSQL

